fix path to 'generated' directory
fixes this error when trying to compile odds (note missing '/' between 'compiled' and 'teisimple.odd'):

```
2015-06-13 23:14:05,683 [Thread-66] ERROR (EmbeddedDownload.java [stream]:143) - java.io.IOException: Resource /db/apps/tei-simple/odd/compiledteisimple.odd not found.
2015-06-13 23:14:05,683 [Thread-66] ERROR (EmbeddedDownloadThread.java [run]:100) - java.io.IOException: Resource /db/apps/tei-simple/odd/compiledteisimple.odd not found.
2015-06-13 23:14:05,694 [eXistThread-77] WARN  (Transform.java [fatalError]:817) - XSL transform reports fatal error: Processing terminated by xsl:message at line -1 in null
net.sf.saxon.expr.instruct.TerminationException: Processing terminated by xsl:message at line -1 in null
...
```